backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Danh sách sản phẩm"
    folder: "_products" # CMS sẽ tự tạo thư mục này để lưu file dữ liệu
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tên sản phẩm", name: "title", widget: "string" }
      - { label: "Giá tiền (VNĐ)", name: "price", widget: "string" }
      - { label: "Ảnh đại diện", name: "image", widget: "image" }
      - { label: "Mô tả chi tiết", name: "body", widget: "markdown" }