backend:
  name: github
  repo: HONGANH20212/MORACHI
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "products"
    label: "Sản Phẩm"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tên sản phẩm", name: "title", widget: "string"}
      - {label: "Thương hiệu", name: "brand", widget: "string"}
      - {label: "Ảnh sản phẩm", name: "thumbnail", widget: "image"}
      - {label: "Giá bán hiện tại", name: "current_price", widget: "string"}
      - {label: "Giá cũ", name: "old_price", widget: "string", required: false}
      - {label: "Giảm giá", name: "discount", widget: "string", required: false}